SELECT * FROM Worker; -- Reading all columns

-- Selecting specific column
SELECT FIRST_NAME,LAST_NAME FROM Worker;

-- Conditions
SELECT * FROM Worker WHERE SALARY=100000;
SELECT * FROM Worker WHERE SALARY>100000;

-- AND,OR,IN,NOT
SELECT * FROM Worker WHERE `SALARY` IN (100000,300000);
SELECT * FROM Worker WHERE `SALARY` NOT IN (100000,300000);
SELECT * FROM Worker WHERE SALARY>100000 AND `DEPARTMENT`='Admin';
SELECT * FROM Worker WHERE SALARY>200000 OR `DEPARTMENT`="Admin";

-- Sorting
SELECT * FROM Worker ORDER BY `SALARY` DESC;

-- Grouping
SELECT `DEPARTMENT`,COUNT(*),AVG(`SALARY`),MIN(`SALARY`),MAX(`SALARY`),SUM(`SALARY`) FROM Worker GROUP BY `DEPARTMENT`;
