SELECT * FROM worker;

-- Selecting specific column
SELECT FIRST_NAME,LAST_NAME FROM worker;

-- Conditions
SELECT * FROM worker WHERE SALARY=100000;
SELECT * FROM worker WHERE SALARY>100000;

-- AND,OR,IN,NOT
SELECT * FROM worker WHERE `SALARY` IN (100000,300000);
SELECT * FROM worker WHERE `SALARY` NOT IN (100000,300000);
SELECT * FROM worker WHERE SALARY>100000 AND `DEPARTMENT`='Admin';
SELECT * FROM worker WHERE SALARY>200000 OR `DEPARTMENT`="Admin";

-- Sorting
SELECT * FROM worker ORDER BY `SALARY` DESC;

-- Grouping
SELECT `DEPARTMENT`,COUNT(*),AVG(`SALARY`),MIN(`SALARY`),MAX(`SALARY`),SUM(`SALARY`) FROM worker GROUP BY `DEPARTMENT`;
